In [2]:
import pandas as pd
import numpy as np

In [6]:
pub=pd.read_csv(r"C:\Users\sanja\Downloads\open_pubs.csv",
               header=None, keep_default_na=False)
pub.head()

0                   1                                                  2  \
0  22          Anchor Inn        Upper Street, Stratford St Mary, COLCHESTER   
1  36  Ark Bar Restaurant  Ark Bar And Restaurant, Cattawade Street, Bran...   
2  74           Black Boy  The Lady Elizabeth, 7 Market Hill, SUDBURY, Su...   
3  75         Black Horse        Lower Street, Stratford St Mary, COLCHESTER   
4  76          Black Lion                      Lion Road, Glemsford, SUDBURY   

          3       4        5          6         7        8  
0   CO7 6LW  604749   234404  51.970379  0.979340  Babergh  
1  CO11 1RH  610194   233329  51.958698  1.057832  Babergh  
2  CO10 2EA  587334   241316  52.038595  0.729915  Babergh  
3   CO7 6JS  622675 -5527598         \N        \N  Babergh  
4  CO10 7RF  622675 -5527598         \N        \N  Babergh

### Add Column Name first

In [7]:
pub.columns=['fsa_id','name','address','postcode','easting','northing','latitude','longitude','local_authority']
pub.head()

fsa_id                name  \
0      22          Anchor Inn   
1      36  Ark Bar Restaurant   
2      74           Black Boy   
3      75         Black Horse   
4      76          Black Lion   

                                             address  postcode  easting  \
0        Upper Street, Stratford St Mary, COLCHESTER   CO7 6LW   604749   
1  Ark Bar And Restaurant, Cattawade Street, Bran...  CO11 1RH   610194   
2  The Lady Elizabeth, 7 Market Hill, SUDBURY, Su...  CO10 2EA   587334   
3        Lower Street, Stratford St Mary, COLCHESTER   CO7 6JS   622675   
4                      Lion Road, Glemsford, SUDBURY  CO10 7RF   622675   

   northing   latitude longitude local_authority  
0    234404  51.970379  0.979340         Babergh  
1    233329  51.958698  1.057832         Babergh  
2    241316  52.038595  0.729915         Babergh  
3  -5527598         \N        \N         Babergh  
4  -5527598         \N        \N         Babergh

In [8]:
pub.shape

(51331, 9)

In [9]:
pub.columns

Index(['fsa_id', 'name', 'address', 'postcode', 'easting', 'northing',
       'latitude', 'longitude', 'local_authority'],
      dtype='object')

In [10]:
pub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51331 entries, 0 to 51330
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   fsa_id           51331 non-null  int64 
 1   name             51331 non-null  object
 2   address          51331 non-null  object
 3   postcode         51331 non-null  object
 4   easting          51331 non-null  int64 
 5   northing         51331 non-null  int64 
 6   latitude         51331 non-null  object
 7   longitude        51331 non-null  object
 8   local_authority  51331 non-null  object
dtypes: int64(3), object(6)
memory usage: 3.5+ MB


In [12]:
pub.isna().sum()

fsa_id             0
name               0
address            0
postcode           0
easting            0
northing           0
latitude           0
longitude          0
local_authority    0
dtype: int64

**There are missing value and are named as `\N`. lets check how many such rows we have in our dataset and remove those rows.**

In [15]:
def change_N_to_nan(col_val):
    if col_val==r'\N':
        return np.nan
    else:
        return col_val

pub['fsa_id']=pub['fsa_id'].apply(change_N_to_nan)
pub['name']=pub['name'].apply(change_N_to_nan)
pub['address']=pub['address'].apply(change_N_to_nan)
pub['postcode']=pub['postcode'].apply(change_N_to_nan)
pub['easting']=pub['easting'].apply(change_N_to_nan)
pub['northing']=pub['northing'].apply(change_N_to_nan)
pub['latitude']=pub['latitude'].apply(change_N_to_nan)
pub['longitude']=pub['longitude'].apply(change_N_to_nan)
pub['local_authority']=pub['local_authority'].apply(change_N_to_nan)

In [16]:
pub.isna().sum()

fsa_id               0
name                 0
address              0
postcode             0
easting              0
northing             0
latitude           767
longitude          767
local_authority      0
dtype: int64

In [17]:
pub.dropna(axis=0, inplace=True)
pub.isna().sum()

fsa_id             0
name               0
address            0
postcode           0
easting            0
northing           0
latitude           0
longitude          0
local_authority    0
dtype: int64

#### Longitude and Latitude must be numeric type

In [18]:
pub['longitude']=pub['longitude'].astype(float)
pub['latitude']=pub['latitude'].astype(float)

In [19]:
pub.dtypes

fsa_id               int64
name                object
address             object
postcode            object
easting              int64
northing             int64
latitude           float64
longitude          float64
local_authority     object
dtype: object

### Total Pub

In [20]:
pub['name'].nunique()

35809

### Total Local Authorities

In [21]:
pub['local_authority'].nunique()

360

In [22]:
pub.to_csv(r'C:\Users\sanja\Downloads\pubs_cleaned.csv', index=False)

### Nearby Pubs by latitude and longitude

In [23]:
points=np.array((float(input()),float(input())))
points

51.970379
1.057536


array([51.970379,  1.057536])

#### Convert longitude latitude and longitude to array

In [29]:
arr=np.array([pub['latitude'],pub['longitude']]).T
arr

array([[51.970379,  0.97934 ],
       [51.958698,  1.057832],
       [52.038595,  0.729915],
       ...,
       [53.044998, -2.996966],
       [53.053094, -2.959124],
       [53.076638, -3.050512]])

In [30]:
dis=np.sum((arr-points)**2, axis=1)
dis

array([6.11461442e-03, 1.36533377e-04, 1.11988942e-01, ...,
       1.75937925e+01, 1.73058293e+01, 1.80998673e+01])

In [31]:
pub['Distance']=dis

In [32]:
pub

fsa_id                                      name  \
0          22                                Anchor Inn   
1          36                        Ark Bar Restaurant   
2          74                                 Black Boy   
5          97                              Brewers Arms   
6         102                              Bristol Arms   
...       ...                                       ...   
51326  597119  Wrexham & District War Memorial Club Ltd   
51327  597127                 Wrexham Lager Social Club   
51328  597130         Wrexham Rail Sports & Social Club   
51329  597131                        Wrexham Rugby Club   
51330  597137                                     Y Tai   

                                                 address  postcode  easting  \
0            Upper Street, Stratford St Mary, COLCHESTER   CO7 6LW   604749   
1      Ark Bar And Restaurant, Cattawade Street, Bran...  CO11 1RH   610194   
2      The Lady Elizabeth, 7 Market Hill, SUDBURY, Su...  CO10 2EA   587334   
5      The Brewers Arms, Bower House Tye, Polstead, C...   CO6 5BZ   598743   
6                         Bristol Hill, Shotley, IPSWICH   IP9 1PU   624624   
...                                                  ...       ...      ...   
51326  Wrexham War Memorial Club Farndon Street, Wrex...  LL13 8DE   333909   
51327                 1 - 3 Union Road, Wrexham, Wrexham  LL13 7SR   333028   
51328  Sports And Social Club, 44 Brook Street, Wrexh...  LL13 7LU   333259   
51329  Wrexham Rugby Club Bryn Estyn Road, Wrexham, W...  LL13 9TY   335808   
51330       Y Tai Railway Road, Brymbo, Wrexham, Wrexham  LL11 5EA   329721   

       northing   latitude  longitude local_authority   Distance  
0        234404  51.970379   0.979340         Babergh   0.006115  
1        233329  51.958698   1.057832         Babergh   0.000137  
2        241316  52.038595   0.729915         Babergh   0.111989  
5        240655  52.028694   0.895650         Babergh   0.029608  
6        233550  51.955042   1.267642         Babergh   0.044380  
...         ...        ...        ...             ...        ...  
51326    350438  53.047100  -2.987319         Wrexham  17.520180  
51327    350563  53.048123  -3.000485         Wrexham  17.629067  
51328    350213  53.044998  -2.996966         Wrexham  17.593792  
51329    351078  53.053094  -2.959124         Wrexham  17.305829  
51330    353785  53.076638  -3.050512         Wrexham  18.099867  

[50564 rows x 10 columns]

#### These are the 5 Nearest Pub Locations

In [33]:
pub.sort_values(by='Distance', ascending=True)[:5]

fsa_id                name  \
29       591           Royal Oak   
60       797          The Grange   
1         36  Ark Bar Restaurant   
52       775       The Crown Inn   
3987   47315       Skinners Arms   

                                                address  postcode  easting  \
29    Royal Oak, East End Lane, East Bergholt, COLCH...   CO7 6XA   609998   
60    The Grange Country Park, Straight Road, East B...   CO7 6UX   609841   
1     Ark Bar And Restaurant, Cattawade Street, Bran...  CO11 1RH   610194   
52    Crown Inn, Cattawade Street, Brantham, MANNING...  CO11 1RE   610209   
3987                       Station Road, Lawford, Essex  CO11 1DX   610493   

      northing   latitude  longitude local_authority  Distance  
29      235171  51.975311   1.056110         Babergh  0.000026  
60      235186  51.975506   1.053837         Babergh  0.000040  
1       233329  51.958698   1.057832         Babergh  0.000137  
52      233104  51.956673   1.057912         Babergh  0.000188  
3987    231873  51.945514   1.061287        Tendring  0.000632

In [37]:
 # get the output for all commands
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

### Max and min longitude and lattitude

In [40]:
pub['latitude'].max()
pub['latitude'].min()

60.764969

49.892485

In [41]:
pub['longitude'].max()
pub['longitude'].min()

1.757763

-7.384525